name: Start Elasticsearch Service

schedules:
  - cron: '0 * * * *' # Every hour
    displayName: Every hour
    branches:
      include:
        - master

pool:
  name: 'hmcts-cftptl-agent-pool'

jobs:
  - job: StartElasticsearchService
    displayName: Start Elasticsearch Service
    steps:
      - checkout: self
        clean: true

      - task: DownloadSecureFile@1
        name: elkprivatekey
        inputs:
          secureFile: 'elk_private_key'

      - script: chmod 600 $(elkprivatekey.secureFilePath)
        displayName: 'Set permissions on private key'

      - script: ./scripts/vm/restart-es-service.sh staging $(elkprivatekey.secureFilePath)
        displayName: 'Start Elasticsearch Staging'

      - script: ./scripts/vm/restart-es-service.sh demo $(elkprivatekey.secureFilePath)
        displayName: 'Start Elasticsearch Demo'

      # - script: ./scripts/vm/restart-es-service.sh perftest $(elkprivatekey.secureFilePath)
      #   displayName: 'Start Elasticsearch Perftest'

      # - script: ./scripts/vm/restart-es-service.sh ithc $(elkprivatekey.secureFilePath)
      #   displayName: 'Start Elasticsearch ITHC'
