name: Start Elasticsearch Service

schedules:
  - cron: '45 6 * * 1-5' # Every weekday at 6:45am BST
    displayName: Weekdays @ 6:45am
    branches:
      include:
        - master

trigger:
  branches:
    include:
      - master

pool:
  name: 'hmcts-cftptl-agent-pool'

jobs:
  job: StartElasticsearchService
  displayName: Start Elasticsearch Service
  steps:
    - checkout: self
      clean: true

    - task: DownloadSecureFile@1
      name: elkprivatekey
      inputs:
        secureFile: 'elk_private_key'

    - script: ./$(System.DefaultWorkingDirectory)/scripts/vm/restart-es-service.sh staging $(elkprivatekey.secureFilePath)
      displayName: 'Start Elasticsearch Staging'

    - script: ./$(System.DefaultWorkingDirectory)/scripts/vm/restart-es-service.sh demo $(elkprivatekey.secureFilePath)
      displayName: 'Start Elasticsearch Demo'

    - script: ./$(System.DefaultWorkingDirectory)/scripts/vm/restart-es-service.sh perftest $(elkprivatekey.secureFilePath)
      displayName: 'Start Elasticsearch Perftest'

    - script: ./$(System.DefaultWorkingDirectory)/scripts/vm/restart-es-service.sh ithc $(elkprivatekey.secureFilePath)
      displayName: 'Start Elasticsearch ITHC'
