name: '🌍 Skip auto shutdown'
description: Request that an environment is not shutdown (automatically processed)
title: "PR-465"
body:
- type: input
  id: form_change_jira_id
  attributes:
    label: Change or Jira reference
    placeholder: "{{ env.PULL_REQUEST }}"
  validations:
    required: true

- type: dropdown
  id: form_business_area
  attributes:
    label: Business area
    options:
      - CFT
      - Cross-Cutting
    default: 0
  validations:
    required: true
    
- type: dropdown
  id: form_environment
  attributes:
    label: Environment
    description: "If AAT / Staging then you may want to also select PTL for Jenkins and Preview / Dev if you need to do a pull request"
    multiple: true
    options: 
      - Sandbox
      - AAT / Staging
      - Preview / Dev 
      - Test / Perftest 
      - Demo
      - ITHC 
      - PTL
    default: 0
  validations:
    required: true
      
- type: input
  id: form_start_date
  attributes:
    label: Skip shutdown start date
    description: "DD-MM-YYYY - date covers shutdown period, 20:00 to 20:00 the following day"
    placeholder: "{{ env.START_DATE }}"
  validations:
    required: true
    
- type: input
  id: form_end_date
  attributes:
    label: Skip shutdown end date
    description: "DD-MM-YYYY - Defaults to start date. 20:00 shutdown job will skip provided clusters on this date."
    placeholder: "{{ env.END_DATE }}"
  validations:
    required: false

- type: dropdown
  id: form_stay_on_late
  attributes:
    label: Do you need this exclusion past 23:00?
    description: Default is set to no. Shutdown of all environments will occur at 23:00 unless the below is ticked.
    multiple: false
    options: 
      - 'No'
      - 'Yes'
    default: 0
  validations:
    required: true
