name: "🌍 Skip auto shutdown"
description: Request that an environment is not shutdown (automatically processed). For more details, refer to the [README](https://github.com/hmcts/auto-shutdown). Please note for any cancel requests, use the cancel label github.

body:
  - type: input
    id: form_change_jira_id
    attributes:
      label: Change or Jira reference
      description: "Provide the Change or Jira reference related to this request. Justification for exclusion? Provide a clear reason for the exclusion."
    validations:
      required: true

  - type: input
    id: form_justification
    attributes:
      label: Justification for exclusion?
      description: "Provide a clear reason for the exclusion."
    validations:
      required: true

  - type: dropdown
    id: form_business_area
    attributes:
      label: Business area
      description: "Select the business area. Bastion servers are considered part of Cross-Cutting. If you need these but this request is for CFT, raise a separate request for the bastion servers."
      options:
        - CFT
        - Cross-Cutting
    validations:
      required: true

  - type: input
    id: form_team_name
    attributes:
      label: Team/Application Name
      description: "The name of the team or application making the request"
    validations:
      required: true

  - type: dropdown
    id: form_environment
    attributes:
      label: Environment
      description: "Select the environment. If AAT / Staging, you may want to also select PTL for Jenkins and Preview / Dev if you need to do a pull request."
      multiple: true
      options:
        - Sandbox
        - AAT / Staging
        - Preview / Dev
        - Test / Perftest
        - Demo
        - ITHC
        - PTL
    validations:
      required: true

  - type: input
    id: form_start_date
    attributes:
      label: Skip shutdown start date
      description: "Enter the start date in DD-MM-YYYY format. If the environment is needed on Saturday & Sunday, the start date should include Friday"
    validations:
      required: true

  - type: input
    id: form_end_date
    attributes:
      label: Skip shutdown end date
      description: "Enter the end date in DD-MM-YYYY format. Dates are inclusive, only include required dates. Leave blank to exclude shutdown for one night only"
    validations:
      required: false

  - type: dropdown
    id: form_stay_on_late
    attributes:
      label: Do you need this exclusion past 11pm?
      description: This is the current time zone. Most people only need an extra couple of hours past the default 8pm, select 'Yes' if you need the environment to stay up the whole night.
      multiple: false
      options:
        - "No"
        - "Yes"
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        **Note:** If you need to delete a request, please add the cancel label on your request.