name: 'Test changes in a pull request'
description: Test the changes you are making to this repo in a pull request by using this issue template
labels: ["pull-request"]
body: |
  Change or Jira reference: $JIRA_REF
  Business area: $BUSINESS_AREA
  Environment: $ENVIRONMENT
  Skip shutdown start date: $START_DATE
  Skip shutdown end date: $END_DATE
  Do you need this exclusion past 23:00?: "No"

