name: Skip auto shutdown request
description: Request the days that you want an environment to stay up
body:

- type: input
  attributes:
    label: Why do you need the auto shutdown skipped?

- type: dropdown
  id: download
  attributes:
    label: Business area
    options:
      - cft
      - cross-cutting
  validations:
    required: true
    
- type: dropdown
  id: Environment
  attributes:
    label: Environment
    multiple: true
    options:
      - Sandbox
      - AAT / Staging
      - Preview / Dev
      - Test / Perftest
      - Demo
      - ITHC
  validations:
    required: true
      
- type: input
  id: Start_Date
  attributes:
    label: Skip shutdown start date
    placeholder: "DD-MM-YYYY"
  validations:
    required: true
    
- type: input
  id: End_Date
  attributes:
    label: Skip shutdown end date
    description: "Defaults to current day"
    placeholder: "DD-MM-YYYY"
  validations:
    required: false
