name: CFT PTL Stop - 19:00

on:
  workflow_dispatch:

  schedule:
    # 19:00 UK during BST (UTC+1)
    - cron: '0 18 * * *'

env:
  SELECTED_AREA: CFT
  SELECTED_ENV: PTL
  SELECTED_MODE: stop
  DEV_ENV: ${{ secrets.DEV_ENV }}

permissions:
  id-token: write

jobs:
  aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
          allow-no-subscriptions: true

      - name: Stop AKS - CFT PTL
        run: ./scripts/aks/manual-start-stop.sh stop

  appgateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
          allow-no-subscriptions: true

      - name: Stop App Gateway - CFT PTL
        run: ./scripts/appgateway/manual-start-stop.sh stop

  flexible-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
          allow-no-subscriptions: true

      - name: Stop Flexible Server - CFT PTL
        run: ./scripts/flexible-server/manual-start-stop.sh stop

  vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
          allow-no-subscriptions: true

      - name: Stop VM - CFT PTL
        run: ./scripts/vm/manual-start-stop.sh stop

  vmss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
          allow-no-subscriptions: true

      - name: Stop VMSS - CFT PTL
        run: ./scripts/vmss/manual-start-stop.sh stop

  mysql-flexible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
          allow-no-subscriptions: true

      - name: Stop MySQL Flexible Server - CFT PTL
        run: ./scripts/mysql-flexible/manual-start-stop.sh stop
