name: bastion-auto-start
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * 1-5" # Every weekday at 6:30am BST
env:
  DEV_ENV: ${{ secrets.DEV_ENV }}
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      ## Production is included here to allow for select resoucres to be started. Only resoucres tagged with autoShutdown: true will be started.
      - name: Production - Bastion Auto Start
        run: ./scripts/bastion/auto-start-stop.sh start production
        env:
          DEV_ENV: ${{ env.DEV_ENV }}

      - name: Staging - Bastion Auto Start
        run: ./scripts/bastion/auto-start-stop.sh start staging
        env:
          DEV_ENV: ${{ env.DEV_ENV }}

      - name: Sandbox - Bastion Auto Start
        run: ./scripts/bastion/auto-start-stop.sh start sandbox
        env:
          DEV_ENV: ${{ env.DEV_ENV }}

      - name: Output log file
        run: ./scripts/common/log-output.sh
