name: elasticsearch-auto-start
on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * 1-5' # Every weekday at 6:45am BST
env:
  DEV_ENV: ${{ secrets.DEV_ENV }}
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .ssh Directory
        run: mkdir -p ~/.ssh

      - name: Download ELK Private Key
        run: |
          echo "${{ secrets.ELK_PRIVATE_KEY }}" > ~/.ssh/elk_private_key
          ls -la ~/.ssh

      - name: Set Permissions
        run: chmod 600 ~/.ssh/elk_private_key

      - name: Restart Elasticsearch Staging
        run: ./scripts/vm/restart-es-service.sh staging

      - name: Restart Elasticsearch Demo
        run: ./scripts/vm/restart-es-service.sh demo

      - name: Restart Elasticsearch Perftest
        run: ./scripts/vm/restart-es-service.sh perftest

      - name: Restart Elasticsearch ITHC
        run: ./scripts/vm/restart-es-service.sh ithc
