name: Housekeeping Shutdown form
run-name: Housekeeping json file
on:
  schedule:
    - cron:  '00 18 * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.PLATFORM_USER_TOKEN }}
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ env.GH_TOKEN }}
     
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python-dateutil
        run: |
          pip3 install python-dateutil
          
      - name: Delete old entries
        continue-on-error: true
        run: |
          python housekeeping.py

      - name: Commit to master
        continue-on-error: true
        if: env.JSON_FILE_EXISTS == 'true'
        run: |
          git config user.name hmcts-platform-operations
          git config user.email github-platform-operations@hmcts.net
          git add .
          git commit -m "housekeeping"
          git push
      
      - name: Close Stale Issues
        uses: actions/stale@v8.0.0
        with:
          days-before-stale: 7
          only-labels: Error in form


