name: Manual Start / Stop
on:
  workflow_dispatch:
    inputs:
      SELECTED_MODE:
        type: choice
        description: "MODE"
        options:
          - start
          - stop
      SELECTED_AREA:
        type: choice
        description: "Business area"
        options:
          - SDS
          - CFT
      SELECTED_ENV:
        type: choice
        description: "Environment"
        options:
          - Sandbox
          - AAT / Staging
          - Preview / Dev
          - Test / Perftest
          - Demo
          - ITHC
          - PTL
          - PTLSBOX
env:
  SELECTED_AREA: ${{ inputs.SELECTED_AREA }}
  SELECTED_ENV: ${{ inputs.SELECTED_ENV }}
  SELECTED_MODE: ${{ inputs.SELECTED_MODE }}
  DEV_ENV: ${{ secrets.DEV_ENV }}
permissions:
  id-token: write
jobs:
  aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: AKS Manual ${{ inputs.SELECTED_MODE }} in ${{ inputs.SELECTED_AREA }} ${{ inputs.SELECTED_ENV }} Environment 
        run: ./scripts/aks/manual-start-stop.sh ${{ inputs.SELECTED_MODE }}
  appgateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: App Gateway Manual ${{ inputs.SELECTED_MODE }} in ${{ inputs.SELECTED_AREA }} ${{ inputs.SELECTED_ENV }} Environment 
        run: ./scripts/appgateway/manual-start-stop.sh ${{ inputs.SELECTED_MODE }}
  flexible-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Flexible Server Manual ${{ inputs.SELECTED_MODE }} in ${{ inputs.SELECTED_AREA }} ${{ inputs.SELECTED_ENV }} Environment 
        run: ./scripts/flexible-server/manual-start-stop.sh ${{ inputs.SELECTED_MODE }}
  vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: VM Manual ${{ inputs.SELECTED_MODE }} in ${{ inputs.SELECTED_AREA }} ${{ inputs.SELECTED_ENV }} Environment 
        run: ./scripts/vm/manual-start-stop.sh ${{ inputs.SELECTED_MODE }}
  vmss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: VMSS Manual ${{ inputs.SELECTED_MODE }} in ${{ inputs.SELECTED_AREA }} ${{ inputs.SELECTED_ENV }} Environment 
        run: ./scripts/vmss/manual-start-stop.sh ${{ inputs.SELECTED_MODE }}
