name: storage-sftp-auto-enable
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 1-5" # Every weekday at 6:30am BST
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: sftp enable
        run: ./scripts/blob-storage/enable_sftp.sh

      - name: Output log file
        run: ./scripts/common/log-output.sh

      - name: Wait for SFTP Servers to start
        run: sleep 300
        
      - name: sftp status check
        run: ./scripts/blob-storage/sftp-check-status.sh start ${{ secrets.SHUTDOWN_NOTIFICATIONS_WEBHOOK }}
