name: storage-sftp-auto-enable
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 1-5" # Every weekday at 6:30am BST
env:
  DEV_ENV: ${{ secrets.DEV_ENV }}
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Staging - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh staging
        env:
          DEV_ENV: ${{ env.DEV_ENV }}
      - name: Testing - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh testing
        env:
          DEV_ENV: ${{ env.DEV_ENV }}
      - name: Demo - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh demo
        env:
          DEV_ENV: ${{ env.DEV_ENV }}
      - name: Development - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh development
        env:
          DEV_ENV: ${{ env.DEV_ENV }}
      - name: Sandbox - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh sandbox
        env:
          DEV_ENV: ${{ env.DEV_ENV }}
      - name: ITHC - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh ithc
        env:
          DEV_ENV: ${{ env.DEV_ENV }}
      - name: Untagged - enable sftp
        run: ./scripts/blob-storage/enable_sftp.sh untagged
        env:
          DEV_ENV: ${{ env.DEV_ENV }}

      - name: Output log file
        run: ./scripts/common/log-output.sh

      - name: Wait for SFTP Servers to start
        if: env.DEV_ENV != 'true'
        run: sleep 300

      - name: sftp status check
        if: env.DEV_ENV != 'true'
        run: ./scripts/blob-storage/sftp-check-status.sh start ${{ secrets.SHUTDOWN_NOTIFICATIONS_WEBHOOK }}
