name: VM-auto-start
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1-5' # Every weekday at 6:30am BST
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 2b6fa9d7-7dba-4600-a58a-5e25554997aa # DTS AKS Auto-Shutdown
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: VM Auto Start
        run: ./scripts/vm/auto-start.sh
      - name: VM Auto start status check
        run: ./scripts/vm/vmstatus.sh
